[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.18"

[features]
seeds = false
skip-lint = true

[programs.localnet]
spl_standard = "7bsQoXhTB3B3YxBHoHZQzzza9gTCkbaiV88thC8tXtb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
client = "yarn run ts-node client/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
