[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_standard = "FRw1e2aDNtwGw5zeuysDd88pzwReV4Qaqp3wNwZijaB6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
